class AIReport {
  final int? id; // make nullable
  final int medicalHistoryId;
  final String title;
  final String content;
  final DateTime? createdAt; // make nullable

  AIReport({
    this.id,
    required this.medicalHistoryId,
    required this.title,
    required this.content,
    this.createdAt,
  });

  /// Constructor for creation only (when id and createdAt will be generated by Supabase)
  AIReport.create({
    required this.medicalHistoryId,
    required this.title,
    required this.content,
  }) : id = null,
       createdAt = null;

  Map<String, dynamic> toMap() {
    return {
      if (id != null) 'id': id,
      'medical_history_id': medicalHistoryId,
      'title': title,
      'content': content,
      if (createdAt != null) 'created_at': createdAt!.toIso8601String(),
    };
  }

  factory AIReport.fromMap(Map<String, dynamic> map) {
    return AIReport(
      id: map['id'],
      medicalHistoryId: map['medical_history_id'],
      title: map['title'],
      content: map['content'],
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'])
          : null,
    );
  }

  Map<String, dynamic> toJson() => toMap();
  factory AIReport.fromJson(Map<String, dynamic> json) =>
      AIReport.fromMap(json);

  AIReport copyWith({
    int? id,
    int? medicalHistoryId,
    String? title,
    String? content,
    DateTime? createdAt,
  }) {
    return AIReport(
      id: id ?? this.id,
      medicalHistoryId: medicalHistoryId ?? this.medicalHistoryId,
      title: title ?? this.title,
      content: content ?? this.content,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
